INSERT INTO FACILITY(ID,NAME) VALUES (1,'Cuneo');
INSERT INTO BUILDING(ID) VALUES (1);

INSERT INTO FACILITY(ID,NAME) VALUES (2, 'MUNDELEIN');
INSERT INTO BUILDING(ID) VALUES (2);

INSERT INTO FACILITY(ID,NAME) VALUES (3,'201');
INSERT INTO UNIT(ID,CAPACITY,BUILDING_ID) VALUES(3,20,1);
